language: java
branches:
  only:
    - master
install: 
  - mvn install -DskipTests
  - npm install
  - node_modules/grunt-cli/bin/grunt --no-color install
script: "mvn verify"
addons:
  sauce_connect:
    username: mycellar
    access_key:
      secure: "KSHoqJWTbru0RKo3YZg3gxcgk0xltsG18pBvnl54d0cY1lPc3w7ZFkt9fTofaIuaWrg7zBj00/tORCsCFxltJh06VHLC0QlBL5mJZim0u3mJJ+kuK09belsBAvvZpMRa8mSpMTnew9loXDMM/SSxKapgi/ZLQp+koGA2i50f56M="
    
