language: java
branches:
  only:
  - master
install:
- mvn install -DskipTests
- npm install
- node_modules/grunt-cli/bin/grunt --no-color install
script: mvn verify jacoco:report
after_script:
- node_modules/grunt-cli/bin/grunt coverage
- mvn coveralls:jacoco
addons:
  sauce_connect: true
env:
  global:
  - secure: eRY/RT7ck1FDfF7hOVLd2gfCbAJseozcU5hXu3HbeDJLzvfoLeCxQGAzBK5j07vRTIwYTa0Hknv3vMUmWneZLAwIn0MtQMdK3eTet6yfqcPgXQKe0J8RGmafp0tubVvWTcGNrqKZkVR+X99p1Nbn49j38ApL2wS2oozXmlQz2Jw=
  - secure: SoCr2OPDLX7v+ZV7+BkMZ32kJALmxtZrDspll69VkdtEwUywAgVJdMt0hg6fkHO9v6H/5IDzJ4AbUY3t/MCQo2xkLDwag93SFkyYExUuv8IuTDN/EV/OBTVi/yxCsLHGdbbkiMfvDu2RrbMDlbxxPmRQnFhE8zIf3tCmA6YoBCQ=
