language: java
branches:
  only:
    - master
install: 
  - mvn install -DskipTests
  - npm install
  - node_modules/grunt-cli/bin/grunt --no-color install
script: "mvn verify"
env:
  global:
    - secure: Aqza1ue7fhjSkwrHrY3QrAOFcrP+l2Psk9Cvr/WwzFgKhZ6p4vdIqvm1tb7Pjs2niDurZ4QucWtNt4pPVboX0Xs4TrNwKOkcV+b8QshXiXJbG4l5t2w0dj8H9Nepy7eCCPDJKtk5Ts2UanijVwrmlHLjRaJ4wA4YBcQQ61qwwNA=
    - secure: YerFM9ixD31W3BLOwZI3uf1JWSs/+7nZQvRWq5lpn3Q11P7IlcEPwJhW9K1gBoLlVCQSDZdqsSxeizjqtGO0B/FWoo5aOqS9J+A/C6Yz1XyuNiVzWdPkHrLDO3htVA8rzlFhJmFmvXFcgp+drF6k+bRRT/8MWczOfsL9nRm0dlw=
addons:
  sauce_connect: true
