language: java
branches:
  only:
    - master
install: 
  - mvn install -DskipTests
  - npm install
  - node_modules/grunt-cli/bin/grunt --no-color install
script: "mvn verify"
env:
  global:
    - secure: Y0S8iOsGoEOF3+XbtqqcKqLvBL1QaDtQ4Yfj60M51NfYkJYWq3W1pL1+JdqS23cbK0noZTd4IFxdrWCOJHXFVCK23Ps8SStkJrXwb/HAOjWOk18oDIiq3MkzKXrA6Vh4te836CmqIjcVZeX3mzmqWG1QAULdganpyPKXcAayTUE=
    - secure: XYM+ZKzVzfd/BZuZQMxWrbp0VZj/oxl85EqduIl6Hi92SdrDaaPaUUdZ6UyDFylpigKrf2N5pum0rp4KfoX42K1nFayc2fp7nkLAyS1MTj+WfeFjjIZoOprsf9Csqq82JQvBXqXVN3xvAWEKdYTlogj9cvdVv+BXh37G35QpIO4=
addons:
  sauce_connect: true
