language: java
branches:
  only:
    - master
env:
  - secure: F3tDvZFEoSgIurNR3jfUKIU8Yev3SsONNr4/uk+ZqdY47OT1WfnxIVQC6XrVkAIQpnOVA1NhPXuSAeFDIynX0imwnWxpYDyhQla30Qj3F1ra+JWZaK8heKS3V3C7ZmQeHppxZ8YguYhZ/lmS/c3FegivismRlzfrkT0VyYytcM4=
  - secure: qKvicEWPuhm2pT+4OI5ay7fBj/qzPIXpMQUUwMFWbLYaPPigv5ksNMNESxz4zm+JzUxp9bfJQtAzEbYOAeOjhmYhhpFJ2lPIO1BMxtMGv+jkvko4V7equAgpfqlqV/V2Xmd5j5+DdeDCzsMq5iVKWZBM7IaYo2KiENMlOxpgJkA=
install: 
  - mvn install -DskipTests
  - npm install
  - node_modules/grunt-cli/bin/grunt --no-color install
script: "mvn verify"
addons:
  sauce_connect: true
