spring:
  application:
    name: MyCellar
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        show_sql: false
        search:
          analyzer: org.apache.lucene.analysis.fr.FrenchAnalyzer
          default: 
            directory_provider: ram
            worker:
              execution: async
              thread_pool_size: 3
