spring:
  application:
    name: MyCellar
  jpa:
    generate-ddl: false
    properties:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        show_sql: false
        search:
          analyzer: org.apache.lucene.analysis.fr.FrenchAnalyzer
          default: 
            directory_provider: ram
            worker:
              execution: async
              thread_pool_size: 3
---
spring:
  profiles: mysql
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: h2
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
