spring:
  application:
    name: MyCellar
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        search:
          analyzer: org.apache.lucene.analysis.fr.FrenchAnalyzer
          default: 
            directory_provider: ram
            worker:
              execution: async
              thread_pool_size: 3
